# 必须配置，或在环境变量中配置也可
OPENAI_API_KEY: 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  # sk-XXXX更改为你的api key,可从此处获取 https://platform.openai.com/account/api-keys
HTTPS_PROXY: socks5://127.0.0.1:7890  # 本地部署是必须配置，请查看自己的代理软件，clash的默认端口为7890,无需更改

PORT: 5000    # 运行端口
API_URL: https://api.peanutsplash.top

# SQL SERVER 设置
SQL_SERVER: 127.0.0.1
SQL_PORT: 3306
SQL_USERNAME: root
SQL_PASSWORD: password
DATABASE: chat

WELLCOME_TEXT: "## ChatGPT 网页版    \nCode From [ChatGPT-Web](https://github.com/FaSheep/ChatGPT-Web)"

# 功能性配置，可适当调整
CHAT_CONTEXT_NUMBER_MAX: 7  # 连续对话模式下的上下文最大数量 n，即开启连续对话模式后，将上传本条消息以及之前你和GPT对话的n-1条消息
USER_BALANCE: 1000 # 用户初始余额